// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Watch

#include "../ui.h"

lv_anim_t Boost2_Anim_Main;
lv_anim_t Boost2_Anim_Point;


static uint8_t Switch = 0;
static void Boost2_Anim_MainCB(void *var, int32_t v)
{
    if(v <= 5)
    {
        if(v != 0)
        {
            lv_obj_add_flag(ui_MainIndeotor[v-1], LV_OBJ_FLAG_HIDDEN);

        }
        lv_label_set_text_fmt(ui_SecConut,"%ld",5-v);
    }
    else
    {
        Switch = 1;
        lv_anim_del(Boost2_Anim_Main.var,Boost2_Anim_Main.exec_cb);        
    }
}

static void Boost2_Anim_PointCB(void *var, int32_t v)
{   
     static uint8_t ComplateFlag = 0;
     uint8_t i;

    if(v == 0)
    {
        if(ComplateFlag)
        {
            for (i = 0; i < 12; i++)
            {
                lv_obj_add_flag(ui_SmallPointWhite[i], LV_OBJ_FLAG_HIDDEN);     /// Flags
            }
        }
        if(Switch == 1)
        {
            Boost2_Anim_Del();
        }


    }
    else if(v <= 12)
    {
        lv_obj_clear_flag(ui_SmallPointWhite[v-1], LV_OBJ_FLAG_HIDDEN);
    }
    else if(v == 13)
    {
        ComplateFlag = 1;
    }

}


void ui_BoostModeB_screen_init(void)
{
    uint8_t i;

    ui_BoostModeB = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BoostModeB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_BoostModeB, &ui_img_secondbg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    for (i = 0; i < 5; i++)
    {
        ui_MainIndeotor[i] = lv_img_create(ui_BoostModeB);
        lv_img_set_src(ui_MainIndeotor[i], &ui_img_mainindector_png);
        lv_obj_set_width(ui_MainIndeotor[i], LV_SIZE_CONTENT);   /// 93
        lv_obj_set_height(ui_MainIndeotor[i], LV_SIZE_CONTENT);    /// 83
        lv_obj_set_x(ui_MainIndeotor[i], 47);
        lv_obj_set_y(ui_MainIndeotor[i], -58);
        lv_obj_clear_flag(ui_MainIndeotor[i], LV_OBJ_FLAG_HIDDEN);      /// Flags
        lv_obj_set_align(ui_MainIndeotor[i], LV_ALIGN_CENTER);
        lv_obj_add_flag(ui_MainIndeotor[i], LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
        lv_obj_clear_flag(ui_MainIndeotor[i], LV_OBJ_FLAG_SCROLLABLE);      /// Flags
        lv_img_set_pivot(ui_MainIndeotor[i], -2, 98);
        lv_img_set_angle(ui_MainIndeotor[i], 2880-i*720);
    }

    for (i = 0; i < 12; i++)
    {
        ui_SmallPoint[i] = lv_img_create(ui_BoostModeB);
        lv_img_set_src(ui_SmallPoint[i], &ui_img_smallpoint_png);
        lv_obj_set_width(ui_SmallPoint[i], LV_SIZE_CONTENT);   /// 38
        lv_obj_set_height(ui_SmallPoint[i], LV_SIZE_CONTENT);    /// 26
        lv_obj_set_x(ui_SmallPoint[i], -10);
        lv_obj_set_y(ui_SmallPoint[i], -90);
        lv_obj_set_align(ui_SmallPoint[i], LV_ALIGN_CENTER);
        lv_obj_add_flag(ui_SmallPoint[i], LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
        lv_obj_clear_flag(ui_SmallPoint[i], LV_OBJ_FLAG_SCROLLABLE);      /// Flags
        lv_img_set_pivot(ui_SmallPoint[i], 28, 102);
        lv_img_set_angle(ui_SmallPoint[i], -300*i);
    }

    for (i = 0; i < 12; i++)
    {
        ui_SmallPointWhite[i] = lv_img_create(ui_BoostModeB);
        lv_img_set_src(ui_SmallPointWhite[i], &ui_img_smallpoint_white_png);
        lv_obj_set_width(ui_SmallPointWhite[i], LV_SIZE_CONTENT);   /// 38
        lv_obj_set_height(ui_SmallPointWhite[i], LV_SIZE_CONTENT);    /// 26
        lv_obj_set_x(ui_SmallPointWhite[i], -10);
        lv_obj_set_y(ui_SmallPointWhite[i], -90);
        lv_obj_set_align(ui_SmallPointWhite[i], LV_ALIGN_CENTER);
        lv_obj_add_flag(ui_SmallPointWhite[i], LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
        lv_obj_clear_flag(ui_SmallPointWhite[i], LV_OBJ_FLAG_SCROLLABLE);      /// Flags
        lv_img_set_pivot(ui_SmallPointWhite[i], 28, 102);
        lv_img_set_angle(ui_SmallPointWhite[i], -300*i);
        lv_obj_add_flag(ui_SmallPointWhite[i], LV_OBJ_FLAG_HIDDEN);     /// Flags
    }

    ui_Triangle = lv_img_create(ui_BoostModeB);
    lv_img_set_src(ui_Triangle, &ui_img_triangle_png);
    lv_obj_set_width(ui_Triangle, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Triangle, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_align(ui_Triangle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Triangle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Triangle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_Triangle, 0, -1);

    ui_SecConut = lv_label_create(ui_BoostModeB);
    lv_obj_set_width(ui_SecConut, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SecConut, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SecConut, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_SecConut,"%d",5);
    lv_obj_set_style_text_color(ui_SecConut, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SecConut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SecConut, &ui_font_Seg48, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_anim_init(&Boost2_Anim_Point);
    lv_anim_set_exec_cb(&Boost2_Anim_Point, Boost2_Anim_PointCB);
    lv_anim_set_path_cb(&Boost2_Anim_Point,lv_anim_path_linear);
    lv_anim_set_repeat_count(&Boost2_Anim_Point, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_values(&Boost2_Anim_Point,0,13);
    lv_anim_set_time(&Boost2_Anim_Point, 850);
    lv_anim_set_var(&Boost2_Anim_Point, ui_SmallPointWhite);

    lv_anim_init(&Boost2_Anim_Main);
    lv_anim_set_exec_cb(&Boost2_Anim_Main, Boost2_Anim_MainCB);
    lv_anim_set_path_cb(&Boost2_Anim_Main,lv_anim_path_linear);
    lv_anim_set_repeat_count(&Boost2_Anim_Main, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_values(&Boost2_Anim_Main,0,6);
    lv_anim_set_time(&Boost2_Anim_Main, 5000);
    lv_anim_set_var(&Boost2_Anim_Main, ui_MainIndeotor);
}

void Boost2_AnimBegin()
{
    lv_anim_start(&Boost2_Anim_Main);
    lv_anim_start(&Boost2_Anim_Point);

}


void Boost2_Anim_Del()
{
    lv_anim_del(Boost2_Anim_Point.var,Boost2_Anim_Point.exec_cb);
    // lv_anim_del(Boost2_Anim_Main.var,Boost2_Anim_Main.exec_cb);
}

