// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Watch

#include "../ui.h"
#include <stdio.h>



static void Eye_BodyAnimPath_CB(void *var, int32_t v)
{
    uint8_t i;

    lv_obj_t *Eye_tmp = (lv_obj_t *)var;

    for ( i = 0; i <v; i++)
    {
        lv_obj_add_flag(ui_ImageN[i], LV_OBJ_FLAG_HIDDEN);     /// Flags
        // lv_obj_clear_flag(ui_ImageN[i], LV_OBJ_FLAG_HIDDEN);
    }
    lv_label_set_text_fmt(ui_Label2,"%d",24-v);
    printf("%d\r\n",v);
}




void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_bgg_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_img_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    uint8_t i;

    for (i = 0; i < 24; i++)
    {
        ui_ImageN[i] = lv_img_create(ui_Screen1);
        lv_img_set_src(ui_ImageN[i], &ui_img_akf_png);
        lv_obj_set_width(ui_ImageN[i], LV_SIZE_CONTENT);   /// 27
        lv_obj_set_height(ui_ImageN[i], LV_SIZE_CONTENT);    /// 92
        lv_obj_set_x(ui_ImageN[i], -15);
        lv_obj_set_y(ui_ImageN[i], -63);
        lv_obj_set_align(ui_ImageN[i], LV_ALIGN_CENTER);
        lv_obj_add_flag(ui_ImageN[i], LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
        lv_obj_clear_flag(ui_ImageN[i], LV_OBJ_FLAG_SCROLLABLE);      /// Flags
        lv_img_set_pivot(ui_ImageN[i], 27, 109);
        lv_img_set_angle(ui_ImageN[i], (i+1)*150);
        // lv_obj_add_flag(ui_ImageN[i], LV_OBJ_FLAG_HIDDEN);     /// Flags
    }

    ui_Panel_Num = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel_Num, 120);
    lv_obj_set_height(ui_Panel_Num, 120);
    lv_obj_set_align(ui_Panel_Num, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Num, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Panel_Num, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_Num, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Num, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_Num, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_Num, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Num, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Panel_Num);
    lv_obj_set_width(ui_Panel1, 90);
    lv_obj_set_height(ui_Panel1, 30);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 10);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_Label2,"%d",7274);
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x1DAB07), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel_Num);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Label1, -2);
    lv_obj_set_y(ui_Label1, 21);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Boost");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xDD0E0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label1, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_anim_init(&Indec);
    lv_anim_set_var(&Indec,ui_ImageN);
    lv_anim_set_values(&Indec,0,24);
    lv_anim_set_time(&Indec, 24000);
    lv_anim_set_delay(&Indec, 500);
    lv_anim_set_exec_cb(&Indec, Eye_BodyAnimPath_CB);
    lv_anim_set_path_cb(&Indec,lv_anim_path_linear);
    lv_anim_set_repeat_delay(&Indec,1000);
    lv_anim_set_repeat_count(&Indec, LV_ANIM_REPEAT_INFINITE);
    lv_anim_start(&Indec);


}
