// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Watch

#include "../ui.h"
#include <stdio.h>

uint16_t AngTab[16] = {450,300,150,3600,3450,3300,3150,3000,2850,2700,2550,2400,2250,2100,1950,1800};

lv_obj_t * ui_ImageN[24];
lv_obj_t * ui_SmallIndec1[6];
lv_anim_t Indec;

static void Eye_BodyAnimPath_CB(void *var, int32_t v)
{

    if(v == 0 )
    {
        
    }
    else if(v <= 16  )
    {
        lv_obj_add_flag(ui_ImageN[v-1], LV_OBJ_FLAG_HIDDEN);
    }
    else
    {
        lv_obj_add_flag(ui_SmallIndec1[v-17], LV_OBJ_FLAG_HIDDEN);
    }

    lv_label_set_text_fmt(ui_Label2,"%ld",21-v);

}



void ui_Screen1_screen_init(void)
{
    uint8_t i;

    for (i = 0; i < 16; i++)
    {
        ui_ImageN[i] = lv_img_create(ui_Screen1);
        lv_img_set_src(ui_ImageN[i], &ui_img_akf_png);
        lv_obj_set_width(ui_ImageN[i], LV_SIZE_CONTENT);   /// 27
        lv_obj_set_height(ui_ImageN[i], LV_SIZE_CONTENT);    /// 92
        lv_obj_set_x(ui_ImageN[i], -15);
        lv_obj_set_y(ui_ImageN[i], -63);
        lv_obj_set_align(ui_ImageN[i], LV_ALIGN_CENTER);
        lv_obj_add_flag(ui_ImageN[i], LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
        lv_obj_clear_flag(ui_ImageN[i], LV_OBJ_FLAG_SCROLLABLE);      /// Flags
        lv_img_set_pivot(ui_ImageN[i], 27, 109);
        lv_img_set_angle(ui_ImageN[i], AngTab[i]);
        // lv_obj_add_flag(ui_ImageN[i], LV_OBJ_FLAG_HIDDEN);     /// Flags
    }

    for (i = 0; i < 5; i++)
    {
        ui_SmallIndec1[i] = lv_img_create(ui_Screen1);
        lv_img_set_src(ui_SmallIndec1[i], &ui_img_smallindecotr_1_png);
        lv_obj_set_width(ui_SmallIndec1[i], LV_SIZE_CONTENT);   /// 22
        lv_obj_set_height(ui_SmallIndec1[i], LV_SIZE_CONTENT);    /// 25
        lv_obj_set_x(ui_SmallIndec1[i], 37);
        lv_obj_set_y(ui_SmallIndec1[i], 89);
        lv_obj_set_align(ui_SmallIndec1[i], LV_ALIGN_CENTER);
        lv_obj_add_flag(ui_SmallIndec1[i], LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
        lv_obj_clear_flag(ui_SmallIndec1[i], LV_OBJ_FLAG_SCROLLABLE);      /// Flags
        lv_img_set_pivot(ui_SmallIndec1[i], -27, -80);
        lv_img_set_angle(ui_SmallIndec1[i], -100*i);
        // lv_obj_add_flag(ui_ImageN[i], LV_OBJ_FLAG_HIDDEN);     /// Flags
    }


    lv_label_set_text_fmt(ui_Label2,"%d",7274);


    lv_anim_init(&Indec);
    lv_anim_set_var(&Indec,ui_ImageN);
    lv_anim_set_values(&Indec,0,21);
    lv_anim_set_time(&Indec, 21000);
    // lv_anim_set_delay(&Indec, 1000);
    lv_anim_set_exec_cb(&Indec, Eye_BodyAnimPath_CB);
    lv_anim_set_path_cb(&Indec,lv_anim_path_linear);
    lv_anim_set_repeat_delay(&Indec,1000);
    lv_anim_set_repeat_count(&Indec, LV_ANIM_REPEAT_INFINITE);
    lv_anim_start(&Indec);

}
